#!/bin/bash

# Input file with cookies in 'name: content' format
input_file="cookies.txt"

# Output file in Netscape format
output_file="cookies_netscape.txt"

# Domain and path for the cookies (customize as needed)
domain=".dscryb.com"
path="/"
expiration="0"  # 0 means session cookie
secure="FALSE"  # Set to TRUE if cookies are for HTTPS only
include_subdomains="TRUE"  # Set to FALSE if not applicable

# Write the header for the Netscape cookie file
echo "# Netscape HTTP Cookie File" > "$output_file"
echo "# This file is generated by a script." >> "$output_file"
echo >> "$output_file"

# Read the input cookie file line by line
while IFS= read -r line
do
  # Split only at the first '=' to handle cases where the value contains '='
  name=$(echo "$line" | cut -d '=' -f 1 | xargs)
  content=$(echo "$line" | cut -d '=' -f 2- | xargs)  # Everything after the first '=' is the content

  # Append each cookie in Netscape format
  echo -e "$domain\t$include_subdomains\t$path\t$secure\t$expiration\t$name\t$content" >> "$output_file"

done < "$input_file"

echo "Cookie file generated: $output_file"

